In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder

In [2]:
data=pd.read_csv("car-price-prediction.csv")
data

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5.0
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,"12.7@ 2,700(kgm@ rpm)",5.0
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,22.4 kgm at 1750-2750rpm,5.0
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,"11.5@ 4,500(kgm@ rpm)",5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai i20 Magna,2013,320000,110000,Petrol,Individual,Manual,First Owner,18.5 kmpl,1197 CC,82.85 bhp,113.7Nm@ 4000rpm,5.0
8124,Hyundai Verna CRDi SX,2007,135000,119000,Diesel,Individual,Manual,Fourth & Above Owner,16.8 kmpl,1493 CC,110 bhp,"24@ 1,900-2,750(kgm@ rpm)",5.0
8125,Maruti Swift Dzire ZDi,2009,382000,120000,Diesel,Individual,Manual,First Owner,19.3 kmpl,1248 CC,73.9 bhp,190Nm@ 2000rpm,5.0
8126,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57 kmpl,1396 CC,70 bhp,140Nm@ 1800-3000rpm,5.0
8127,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57 kmpl,1396 CC,70 bhp,140Nm@ 1800-3000rpm,5.0

In [3]:
data.info()
data2=data.copy()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           8128 non-null   object
 1   year           8128 non-null   int64
 2   selling_price  8128 non-null   int64
 3   km_driven      8128 non-null   int64
 4   fuel           8128 non-null   object
 5   seller_type    8128 non-null   object
 6   transmission   8128 non-null   object
 7   owner          8128 non-null   object
 8   mileage        7907 non-null   object
 9   engine         7907 non-null   object
 10  max_power      7913 non-null   object
 11  torque         7906 non-null   object
 12  seats          7907 non-null   float64
dtypes: float64(1), int64(3), object(9)
memory usage: 825.6+ KB

In [4]:
data.describe()

              year  selling_price     km_driven        seats
count  8128.000000   8.128000e+03  8.128000e+03  7907.000000
mean   2013.804011   6.382718e+05  6.981951e+04     5.416719
std       4.044249   8.062534e+05  5.655055e+04     0.959588
min    1983.000000   2.999900e+04  1.000000e+00     2.000000
25%    2011.000000   2.549990e+05  3.500000e+04     5.000000
50%    2015.000000   4.500000e+05  6.000000e+04     5.000000
75%    2017.000000   6.750000e+05  9.800000e+04     5.000000
max    2020.000000   1.000000e+07  2.360457e+06    14.000000

In [5]:
print(data.isnull().sum())
data=data.loc[data.mileage.notnull()]

name               0
year               0
selling_price      0
km_driven          0
fuel               0
seller_type        0
transmission       0
owner              0
mileage          221
engine           221
max_power        215
torque           222
seats            221
dtype: int64

In [6]:
data.isnull().sum()

name             0
year             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
mileage          0
engine           0
max_power        0
torque           1
seats            0
dtype: int64

In [7]:
data["name"].nunique()

1983

In [29]:
print(data["mileage"].str.contains("kmpl").value_counts())
data["mileage"].str.contains("km/kg").value_counts()

mileage
True     7819
False      88
Name: count, dtype: int64

mileage
False    7819
True       88
Name: count, dtype: int64

In [9]:
data[data["mileage"].str.contains("km/kg")].fuel.unique()

array(['LPG', 'CNG'], dtype=object)

In [10]:
datakmpg=data[data["mileage"].str.contains("km/kg")].copy()

In [11]:
datakmpg

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
6,Maruti Wagon R LXI DUO BSIII,2007,96000,175000,LPG,Individual,Manual,First Owner,17.3 km/kg,1061 CC,57.5 bhp,"7.8@ 4,500(kgm@ rpm)",5.0
35,Maruti Alto 800 CNG LXI Optional,2019,330000,10000,CNG,Individual,Manual,Second Owner,33.44 km/kg,796 CC,40.3 bhp,60Nm@ 3500rpm,4.0
90,Maruti Wagon R LXI LPG BSIV,2010,225000,44000,LPG,Dealer,Manual,First Owner,26.2 km/kg,998 CC,58.2 bhp,77Nm@ 3500rpm,5.0
203,Maruti Wagon R LXI CNG,2016,360000,50000,CNG,Individual,Manual,First Owner,26.6 km/kg,998 CC,58.16 bhp,77Nm@ 3500rpm,5.0
402,Maruti Eeco CNG 5 Seater AC,2020,409999,35000,CNG,Individual,Manual,First Owner,20.88 km/kg,1196 CC,61.7 bhp,85Nm@ 3000rpm,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7308,Maruti Alto Green LXi (CNG),2010,155000,70000,CNG,Individual,Manual,Second Owner,26.83 km/kg,796 CC,38.4 bhp,62Nm@ 3000rpm,5.0
7543,Maruti Alto 800 CNG LXI Optional,2019,330000,10000,CNG,Individual,Manual,Second Owner,33.44 km/kg,796 CC,40.3 bhp,60Nm@ 3500rpm,4.0
7642,Chevrolet Spark 1.0 LT LPG,2012,300000,70000,LPG,Individual,Manual,First Owner,13.2 km/kg,995 CC,60.2 bhp,90.3Nm@ 4200rpm,5.0
7733,Maruti Eeco CNG 5 Seater AC BSIV,2015,380000,20000,CNG,Individual,Manual,First Owner,21.94 km/kg,1196 CC,61.7 bhp,85Nm@ 3000rpm,5.0
7913,Maruti Eeco 5 STR With AC Plus HTR CNG,2011,209000,1,CNG,Individual,Manual,Fourth & Above Owner,15.1 km/kg,1196 CC,73 bhp,101Nm@ 3000rpm,5.0

In [12]:
datakmpg['mileage']=datakmpg["mileage"].str.replace("km/kg","")

In [13]:
## kmpl=dist/vol dist/(mass/density) density*(dist/mass)

In [14]:
dataaaa=datakmpg.copy()

In [15]:
datakmpg.loc[datakmpg.fuel=='LPG',"mileage"].astype(float).multiply(1.96)

6       33.908
90      51.352
870     51.352
1511    51.352
1658    33.908
1907    26.362
2108    33.908
2166    33.908
2484    26.362
2518    51.352
2579    51.352
2588    51.352
3010    26.362
3042    37.632
3050    51.352
3216    34.888
3466    21.364
3492    51.352
3751    26.362
3796    33.908
3823    37.632
4045    41.356
4545    37.632
5436    32.536
5437    31.360
5578    33.908
5768    37.632
6007    21.364
6253    37.240
6338    51.352
6856    26.362
7101    25.872
7112    28.224
7245    26.362
7642    25.872
Name: mileage, dtype: float64

In [16]:
datakmpg.loc[datakmpg.fuel=='LPG',"mileage"]=datakmpg.loc[datakmpg.fuel=='LPG',"mileage"].astype(float).multiply(1.96)

In [17]:
datakmpg

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
6,Maruti Wagon R LXI DUO BSIII,2007,96000,175000,LPG,Individual,Manual,First Owner,33.908,1061 CC,57.5 bhp,"7.8@ 4,500(kgm@ rpm)",5.0
35,Maruti Alto 800 CNG LXI Optional,2019,330000,10000,CNG,Individual,Manual,Second Owner,33.44,796 CC,40.3 bhp,60Nm@ 3500rpm,4.0
90,Maruti Wagon R LXI LPG BSIV,2010,225000,44000,LPG,Dealer,Manual,First Owner,51.352,998 CC,58.2 bhp,77Nm@ 3500rpm,5.0
203,Maruti Wagon R LXI CNG,2016,360000,50000,CNG,Individual,Manual,First Owner,26.6,998 CC,58.16 bhp,77Nm@ 3500rpm,5.0
402,Maruti Eeco CNG 5 Seater AC,2020,409999,35000,CNG,Individual,Manual,First Owner,20.88,1196 CC,61.7 bhp,85Nm@ 3000rpm,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7308,Maruti Alto Green LXi (CNG),2010,155000,70000,CNG,Individual,Manual,Second Owner,26.83,796 CC,38.4 bhp,62Nm@ 3000rpm,5.0
7543,Maruti Alto 800 CNG LXI Optional,2019,330000,10000,CNG,Individual,Manual,Second Owner,33.44,796 CC,40.3 bhp,60Nm@ 3500rpm,4.0
7642,Chevrolet Spark 1.0 LT LPG,2012,300000,70000,LPG,Individual,Manual,First Owner,25.872,995 CC,60.2 bhp,90.3Nm@ 4200rpm,5.0
7733,Maruti Eeco CNG 5 Seater AC BSIV,2015,380000,20000,CNG,Individual,Manual,First Owner,21.94,1196 CC,61.7 bhp,85Nm@ 3000rpm,5.0
7913,Maruti Eeco 5 STR With AC Plus HTR CNG,2011,209000,1,CNG,Individual,Manual,Fourth & Above Owner,15.1,1196 CC,73 bhp,101Nm@ 3000rpm,5.0

In [18]:
data["fuel"].unique()

array(['Diesel', 'Petrol', 'LPG', 'CNG'], dtype=object)

In [19]:
encode=LabelEncoder()
label=encode.fit_transform(data.fuel)
data["encoded_fuel"]=label

C:\Users\SAHIL MOHRIL\AppData\Local\Temp\ipykernel_32116\2035816003.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["encoded_fuel"]=label

In [20]:
data

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats,encoded_fuel
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0,1
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5.0,1
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,"12.7@ 2,700(kgm@ rpm)",5.0,3
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,22.4 kgm at 1750-2750rpm,5.0,1
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,"11.5@ 4,500(kgm@ rpm)",5.0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai i20 Magna,2013,320000,110000,Petrol,Individual,Manual,First Owner,18.5 kmpl,1197 CC,82.85 bhp,113.7Nm@ 4000rpm,5.0,3
8124,Hyundai Verna CRDi SX,2007,135000,119000,Diesel,Individual,Manual,Fourth & Above Owner,16.8 kmpl,1493 CC,110 bhp,"24@ 1,900-2,750(kgm@ rpm)",5.0,1
8125,Maruti Swift Dzire ZDi,2009,382000,120000,Diesel,Individual,Manual,First Owner,19.3 kmpl,1248 CC,73.9 bhp,190Nm@ 2000rpm,5.0,1
8126,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57 kmpl,1396 CC,70 bhp,140Nm@ 1800-3000rpm,5.0,1
8127,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57 kmpl,1396 CC,70 bhp,140Nm@ 1800-3000rpm,5.0,1

In [21]:
data['transmission'].unique()
#data=data.loc[:,'transmission_code']
label=encode.fit_transform(data.transmission)
data=data.copy()
data['transmission_encode']=label
data[data['transmission']=='Automatic']

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats,encoded_fuel,transmission_encode
41,Jeep Compass 1.4 Limited Plus BSIV,2019,2100000,5000,Petrol,Individual,Automatic,First Owner,16.0 kmpl,1368 CC,160.77 bhp,250Nm@ 1750-2500rpm,5.0,3,0
44,Maruti Swift Dzire VXi AT,2018,675000,23300,Petrol,Dealer,Automatic,First Owner,18.5 kmpl,1197 CC,83.14 bhp,115Nm@ 4000rpm,5.0,3,0
49,Mercedes-Benz B Class B180,2014,1450000,27800,Diesel,Dealer,Automatic,Second Owner,14.8 kmpl,2143 CC,120.7 bhp,200Nm@ 1250-4000rpm,5.0,1,0
55,Toyota Innova Crysta 2.8 ZX AT BSIV,2016,1650000,127700,Diesel,Dealer,Automatic,Second Owner,11.36 kmpl,2755 CC,171.5 bhp,360Nm@ 1200-3400rpm,7.0,1,0
57,Audi A6 2.0 TDI Technology,2013,1750000,33900,Diesel,Dealer,Automatic,Second Owner,17.68 kmpl,1968 CC,174.33 bhp,380Nm@ 1750-2500rpm,5.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8058,Audi A3 40 TFSI Premium,2017,1689999,8000,Petrol,Dealer,Automatic,First Owner,16.6 kmpl,1798 CC,177.5 bhp,250Nm@ 1250-5000rpm,5.0,3,0
8063,Hyundai Creta 1.6 SX Automatic,2016,890000,40000,Petrol,Dealer,Automatic,First Owner,14.8 kmpl,1591 CC,121.3 bhp,151NM@ 4850rpm,5.0,3,0
8081,Honda City ZXi AT,2005,110000,100000,Petrol,Individual,Automatic,Second Owner,12.0 kmpl,1493 CC,100 bhp,13.1kgm@ 4600rpm,5.0,3,0
8086,Maruti Celerio ZXI AMT BSIV,2018,470000,30000,Petrol,Individual,Automatic,First Owner,23.1 kmpl,998 CC,67.04 bhp,90Nm@ 3500rpm,5.0,3,0
8108,Kia Seltos HTX Plus AT D,2019,1575000,20000,Diesel,Individual,Automatic,First Owner,17.8 kmpl,1493 CC,113.4 bhp,250nm@ 1500-2750rpm,5.0,1,0

In [22]:
data['owner'].unique()
label=encode.fit_transform(data.owner)
data=data.copy()
data['owner_encode']=label
data['max_power'].str.contains("bhp").size-data['max_power'].size

0

In [23]:
data2=data.copy()
data2['max_power']=data['max_power'].str.replace("bhp","")
data2['engine']=data['engine'].str.replace("CC","")
data2

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats,encoded_fuel,transmission_encode,owner_encode
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248,74,190Nm@ 2000rpm,5.0,1,1,0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498,103.52,250Nm@ 1500-2500rpm,5.0,1,1,2
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497,78,"12.7@ 2,700(kgm@ rpm)",5.0,3,1,4
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396,90,22.4 kgm at 1750-2750rpm,5.0,1,1,0
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298,88.2,"11.5@ 4,500(kgm@ rpm)",5.0,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai i20 Magna,2013,320000,110000,Petrol,Individual,Manual,First Owner,18.5 kmpl,1197,82.85,113.7Nm@ 4000rpm,5.0,3,1,0
8124,Hyundai Verna CRDi SX,2007,135000,119000,Diesel,Individual,Manual,Fourth & Above Owner,16.8 kmpl,1493,110,"24@ 1,900-2,750(kgm@ rpm)",5.0,1,1,1
8125,Maruti Swift Dzire ZDi,2009,382000,120000,Diesel,Individual,Manual,First Owner,19.3 kmpl,1248,73.9,190Nm@ 2000rpm,5.0,1,1,0
8126,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57 kmpl,1396,70,140Nm@ 1800-3000rpm,5.0,1,1,0
8127,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57 kmpl,1396,70,140Nm@ 1800-3000rpm,5.0,1,1,0

In [24]:
data2['engine']=data2['engine'].astype(int)
data2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7907 entries, 0 to 8127
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   name                 7907 non-null   object
 1   year                 7907 non-null   int64
 2   selling_price        7907 non-null   int64
 3   km_driven            7907 non-null   int64
 4   fuel                 7907 non-null   object
 5   seller_type          7907 non-null   object
 6   transmission         7907 non-null   object
 7   owner                7907 non-null   object
 8   mileage              7907 non-null   object
 9   engine               7907 non-null   int32
 10  max_power            7907 non-null   object
 11  torque               7906 non-null   object
 12  seats                7907 non-null   float64
 13  encoded_fuel         7907 non-null   int32
 14  transmission_encode  7907 non-null   int32
 15  owner_encode         7907 non-null   int32
dtypes: float64(1), int32(4), int64(3), object(8)
memory usage: 926.6+ KB

In [25]:
data2[data2['max_power'].str.contains(" ")]
data2['max_power'].str.replace(" ",'#').str.rstrip(" ")

0           74#
1       103.52#
2           78#
3           90#
4         88.2#
         ...
8123     82.85#
8124       110#
8125      73.9#
8126        70#
8127        70#
Name: max_power, Length: 7907, dtype: object